package masterdetail.oracle.apps.fnd.master.schema.server;

import oracle.apps.fnd.framework.server.OAEntityDefImpl;
import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DetailEOImpl extends OAEntityImpl {
    public static final int TEAMID = 0;
    public static final int TEAMNAME = 1;
    public static final int TEAMARABICNAME = 2;
    public static final int SHORTNAME = 3;
    public static final int TEAMTYPE = 4;
    public static final int SECRETARY = 5;
    public static final int SECRETARYASSISTANT = 6;
    public static final int ENDDATE = 7;
    public static final int BUDGETFROM = 8;
    public static final int BUDGETTO = 9;
    public static final int DESCRIPTION = 10;
    public static final int CREATIONDATE = 11;
    public static final int CREATEDBY = 12;
    public static final int LASTUPDATEDATE = 13;
    public static final int LASTUPDATEBY = 14;
    public static final int INTATTRIBUTECATEGORY = 15;
    public static final int INTATTRIBUTE1 = 16;
    public static final int INTATTRIBUTE2 = 17;
    public static final int INTATTRIBUTE3 = 18;
    public static final int INTATTRIBUTE4 = 19;
    public static final int INTATTRIBUTE5 = 20;
    public static final int INTATTRIBUTE6 = 21;
    public static final int INTATTRIBUTE7 = 22;
    public static final int INTATTRIBUTE8 = 23;
    public static final int INTATTRIBUTE9 = 24;
    public static final int INTATTRIBUTE10 = 25;
    public static final int INTATTRIBUTE11 = 26;
    public static final int INTATTRIBUTE12 = 27;
    public static final int INTATTRIBUTE13 = 28;
    public static final int INTATTRIBUTE14 = 29;
    public static final int INTATTRIBUTE15 = 30;
    public static final int EXTATTRIBUTECATEGORY = 31;
    public static final int EXTATTRIBUTE1 = 32;
    public static final int EXTATTRIBUTE2 = 33;
    public static final int EXTATTRIBUTE3 = 34;
    public static final int EXTATTRIBUTE4 = 35;
    public static final int EXTATTRIBUTE5 = 36;
    public static final int EXTATTRIBUTE6 = 37;
    public static final int EXTATTRIBUTE7 = 38;
    public static final int EXTATTRIBUTE8 = 39;
    public static final int EXTATTRIBUTE9 = 40;
    public static final int EXTATTRIBUTE10 = 41;
    public static final int EXTATTRIBUTE11 = 42;
    public static final int EXTATTRIBUTE12 = 43;
    public static final int EXTATTRIBUTE13 = 44;
    public static final int EXTATTRIBUTE14 = 45;
    public static final int EXTATTRIBUTE15 = 46;


    private static OAEntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public DetailEOImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = 
                    (OAEntityDefImpl)EntityDefImpl.findDefObject("masterdetail.oracle.apps.fnd.master.schema.server.DetailEO");
        }
        return mDefinitionObject;
    }

    /**Add attribute defaulting logic in this method.
     */
    public void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**Add Entity validation code in this method.
     */
    protected void validateEntity() {
        super.validateEntity();
    }

    /**Gets the attribute value for TeamId, using the alias name TeamId
     */
    public Number getTeamId() {
        return (Number)getAttributeInternal(TEAMID);
    }

    /**Sets <code>value</code> as the attribute value for TeamId
     */
    public void setTeamId(Number value) {
        setAttributeInternal(TEAMID, value);
    }

    /**Gets the attribute value for TeamName, using the alias name TeamName
     */
    public String getTeamName() {
        return (String)getAttributeInternal(TEAMNAME);
    }

    /**Sets <code>value</code> as the attribute value for TeamName
     */
    public void setTeamName(String value) {
        setAttributeInternal(TEAMNAME, value);
    }

    /**Gets the attribute value for TeamArabicName, using the alias name TeamArabicName
     */
    public String getTeamArabicName() {
        return (String)getAttributeInternal(TEAMARABICNAME);
    }

    /**Sets <code>value</code> as the attribute value for TeamArabicName
     */
    public void setTeamArabicName(String value) {
        setAttributeInternal(TEAMARABICNAME, value);
    }

    /**Gets the attribute value for ShortName, using the alias name ShortName
     */
    public String getShortName() {
        return (String)getAttributeInternal(SHORTNAME);
    }

    /**Sets <code>value</code> as the attribute value for ShortName
     */
    public void setShortName(String value) {
        setAttributeInternal(SHORTNAME, value);
    }

    /**Gets the attribute value for TeamType, using the alias name TeamType
     */
    public String getTeamType() {
        return (String)getAttributeInternal(TEAMTYPE);
    }

    /**Sets <code>value</code> as the attribute value for TeamType
     */
    public void setTeamType(String value) {
        setAttributeInternal(TEAMTYPE, value);
    }

    /**Gets the attribute value for Secretary, using the alias name Secretary
     */
    public String getSecretary() {
        return (String)getAttributeInternal(SECRETARY);
    }

    /**Sets <code>value</code> as the attribute value for Secretary
     */
    public void setSecretary(String value) {
        setAttributeInternal(SECRETARY, value);
    }

    /**Gets the attribute value for SecretaryAssistant, using the alias name SecretaryAssistant
     */
    public String getSecretaryAssistant() {
        return (String)getAttributeInternal(SECRETARYASSISTANT);
    }

    /**Sets <code>value</code> as the attribute value for SecretaryAssistant
     */
    public void setSecretaryAssistant(String value) {
        setAttributeInternal(SECRETARYASSISTANT, value);
    }

    /**Gets the attribute value for EndDate, using the alias name EndDate
     */
    public Date getEndDate() {
        return (Date)getAttributeInternal(ENDDATE);
    }

    /**Sets <code>value</code> as the attribute value for EndDate
     */
    public void setEndDate(Date value) {
        setAttributeInternal(ENDDATE, value);
    }

    /**Gets the attribute value for BudgetFrom, using the alias name BudgetFrom
     */
    public Number getBudgetFrom() {
        return (Number)getAttributeInternal(BUDGETFROM);
    }

    /**Sets <code>value</code> as the attribute value for BudgetFrom
     */
    public void setBudgetFrom(Number value) {
        setAttributeInternal(BUDGETFROM, value);
    }

    /**Gets the attribute value for BudgetTo, using the alias name BudgetTo
     */
    public Number getBudgetTo() {
        return (Number)getAttributeInternal(BUDGETTO);
    }

    /**Sets <code>value</code> as the attribute value for BudgetTo
     */
    public void setBudgetTo(Number value) {
        setAttributeInternal(BUDGETTO, value);
    }

    /**Gets the attribute value for Description, using the alias name Description
     */
    public String getDescription() {
        return (String)getAttributeInternal(DESCRIPTION);
    }

    /**Sets <code>value</code> as the attribute value for Description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**Gets the attribute value for CreationDate, using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for CreatedBy, using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LastUpdateBy, using the alias name LastUpdateBy
     */
    public Number getLastUpdateBy() {
        return (Number)getAttributeInternal(LASTUPDATEBY);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateBy
     */
    public void setLastUpdateBy(Number value) {
        setAttributeInternal(LASTUPDATEBY, value);
    }

    /**Gets the attribute value for IntAttributeCategory, using the alias name IntAttributeCategory
     */
    public String getIntAttributeCategory() {
        return (String)getAttributeInternal(INTATTRIBUTECATEGORY);
    }

    /**Sets <code>value</code> as the attribute value for IntAttributeCategory
     */
    public void setIntAttributeCategory(String value) {
        setAttributeInternal(INTATTRIBUTECATEGORY, value);
    }

    /**Gets the attribute value for IntAttribute1, using the alias name IntAttribute1
     */
    public String getIntAttribute1() {
        return (String)getAttributeInternal(INTATTRIBUTE1);
    }

    /**Sets <code>value</code> as the attribute value for IntAttribute1
     */
    public void setIntAttribute1(String value) {
        setAttributeInternal(INTATTRIBUTE1, value);
    }

    /**Gets the attribute value for IntAttribute2, using the alias name IntAttribute2
     */
    public String getIntAttribute2() {
        return (String)getAttributeInternal(INTATTRIBUTE2);
    }

    /**Sets <code>value</code> as the attribute value for IntAttribute2
     */
    public void setIntAttribute2(String value) {
        setAttributeInternal(INTATTRIBUTE2, value);
    }

    /**Gets the attribute value for IntAttribute3, using the alias name IntAttribute3
     */
    public String getIntAttribute3() {
        return (String)getAttributeInternal(INTATTRIBUTE3);
    }

    /**Sets <code>value</code> as the attribute value for IntAttribute3
     */
    public void setIntAttribute3(String value) {
        setAttributeInternal(INTATTRIBUTE3, value);
    }

    /**Gets the attribute value for IntAttribute4, using the alias name IntAttribute4
     */
    public String getIntAttribute4() {
        return (String)getAttributeInternal(INTATTRIBUTE4);
    }

    /**Sets <code>value</code> as the attribute value for IntAttribute4
     */
    public void setIntAttribute4(String value) {
        setAttributeInternal(INTATTRIBUTE4, value);
    }

    /**Gets the attribute value for IntAttribute5, using the alias name IntAttribute5
     */
    public String getIntAttribute5() {
        return (String)getAttributeInternal(INTATTRIBUTE5);
    }

    /**Sets <code>value</code> as the attribute value for IntAttribute5
     */
    public void setIntAttribute5(String value) {
        setAttributeInternal(INTATTRIBUTE5, value);
    }

    /**Gets the attribute value for IntAttribute6, using the alias name IntAttribute6
     */
    public String getIntAttribute6() {
        return (String)getAttributeInternal(INTATTRIBUTE6);
    }

    /**Sets <code>value</code> as the attribute value for IntAttribute6
     */
    public void setIntAttribute6(String value) {
        setAttributeInternal(INTATTRIBUTE6, value);
    }

    /**Gets the attribute value for IntAttribute7, using the alias name IntAttribute7
     */
    public String getIntAttribute7() {
        return (String)getAttributeInternal(INTATTRIBUTE7);
    }

    /**Sets <code>value</code> as the attribute value for IntAttribute7
     */
    public void setIntAttribute7(String value) {
        setAttributeInternal(INTATTRIBUTE7, value);
    }

    /**Gets the attribute value for IntAttribute8, using the alias name IntAttribute8
     */
    public String getIntAttribute8() {
        return (String)getAttributeInternal(INTATTRIBUTE8);
    }

    /**Sets <code>value</code> as the attribute value for IntAttribute8
     */
    public void setIntAttribute8(String value) {
        setAttributeInternal(INTATTRIBUTE8, value);
    }

    /**Gets the attribute value for IntAttribute9, using the alias name IntAttribute9
     */
    public String getIntAttribute9() {
        return (String)getAttributeInternal(INTATTRIBUTE9);
    }

    /**Sets <code>value</code> as the attribute value for IntAttribute9
     */
    public void setIntAttribute9(String value) {
        setAttributeInternal(INTATTRIBUTE9, value);
    }

    /**Gets the attribute value for IntAttribute10, using the alias name IntAttribute10
     */
    public String getIntAttribute10() {
        return (String)getAttributeInternal(INTATTRIBUTE10);
    }

    /**Sets <code>value</code> as the attribute value for IntAttribute10
     */
    public void setIntAttribute10(String value) {
        setAttributeInternal(INTATTRIBUTE10, value);
    }

    /**Gets the attribute value for IntAttribute11, using the alias name IntAttribute11
     */
    public String getIntAttribute11() {
        return (String)getAttributeInternal(INTATTRIBUTE11);
    }

    /**Sets <code>value</code> as the attribute value for IntAttribute11
     */
    public void setIntAttribute11(String value) {
        setAttributeInternal(INTATTRIBUTE11, value);
    }

    /**Gets the attribute value for IntAttribute12, using the alias name IntAttribute12
     */
    public String getIntAttribute12() {
        return (String)getAttributeInternal(INTATTRIBUTE12);
    }

    /**Sets <code>value</code> as the attribute value for IntAttribute12
     */
    public void setIntAttribute12(String value) {
        setAttributeInternal(INTATTRIBUTE12, value);
    }

    /**Gets the attribute value for IntAttribute13, using the alias name IntAttribute13
     */
    public String getIntAttribute13() {
        return (String)getAttributeInternal(INTATTRIBUTE13);
    }

    /**Sets <code>value</code> as the attribute value for IntAttribute13
     */
    public void setIntAttribute13(String value) {
        setAttributeInternal(INTATTRIBUTE13, value);
    }

    /**Gets the attribute value for IntAttribute14, using the alias name IntAttribute14
     */
    public String getIntAttribute14() {
        return (String)getAttributeInternal(INTATTRIBUTE14);
    }

    /**Sets <code>value</code> as the attribute value for IntAttribute14
     */
    public void setIntAttribute14(String value) {
        setAttributeInternal(INTATTRIBUTE14, value);
    }

    /**Gets the attribute value for IntAttribute15, using the alias name IntAttribute15
     */
    public String getIntAttribute15() {
        return (String)getAttributeInternal(INTATTRIBUTE15);
    }

    /**Sets <code>value</code> as the attribute value for IntAttribute15
     */
    public void setIntAttribute15(String value) {
        setAttributeInternal(INTATTRIBUTE15, value);
    }

    /**Gets the attribute value for ExtAttributeCategory, using the alias name ExtAttributeCategory
     */
    public String getExtAttributeCategory() {
        return (String)getAttributeInternal(EXTATTRIBUTECATEGORY);
    }

    /**Sets <code>value</code> as the attribute value for ExtAttributeCategory
     */
    public void setExtAttributeCategory(String value) {
        setAttributeInternal(EXTATTRIBUTECATEGORY, value);
    }

    /**Gets the attribute value for ExtAttribute1, using the alias name ExtAttribute1
     */
    public String getExtAttribute1() {
        return (String)getAttributeInternal(EXTATTRIBUTE1);
    }

    /**Sets <code>value</code> as the attribute value for ExtAttribute1
     */
    public void setExtAttribute1(String value) {
        setAttributeInternal(EXTATTRIBUTE1, value);
    }

    /**Gets the attribute value for ExtAttribute2, using the alias name ExtAttribute2
     */
    public String getExtAttribute2() {
        return (String)getAttributeInternal(EXTATTRIBUTE2);
    }

    /**Sets <code>value</code> as the attribute value for ExtAttribute2
     */
    public void setExtAttribute2(String value) {
        setAttributeInternal(EXTATTRIBUTE2, value);
    }

    /**Gets the attribute value for ExtAttribute3, using the alias name ExtAttribute3
     */
    public String getExtAttribute3() {
        return (String)getAttributeInternal(EXTATTRIBUTE3);
    }

    /**Sets <code>value</code> as the attribute value for ExtAttribute3
     */
    public void setExtAttribute3(String value) {
        setAttributeInternal(EXTATTRIBUTE3, value);
    }

    /**Gets the attribute value for ExtAttribute4, using the alias name ExtAttribute4
     */
    public String getExtAttribute4() {
        return (String)getAttributeInternal(EXTATTRIBUTE4);
    }

    /**Sets <code>value</code> as the attribute value for ExtAttribute4
     */
    public void setExtAttribute4(String value) {
        setAttributeInternal(EXTATTRIBUTE4, value);
    }

    /**Gets the attribute value for ExtAttribute5, using the alias name ExtAttribute5
     */
    public String getExtAttribute5() {
        return (String)getAttributeInternal(EXTATTRIBUTE5);
    }

    /**Sets <code>value</code> as the attribute value for ExtAttribute5
     */
    public void setExtAttribute5(String value) {
        setAttributeInternal(EXTATTRIBUTE5, value);
    }

    /**Gets the attribute value for ExtAttribute6, using the alias name ExtAttribute6
     */
    public String getExtAttribute6() {
        return (String)getAttributeInternal(EXTATTRIBUTE6);
    }

    /**Sets <code>value</code> as the attribute value for ExtAttribute6
     */
    public void setExtAttribute6(String value) {
        setAttributeInternal(EXTATTRIBUTE6, value);
    }

    /**Gets the attribute value for ExtAttribute7, using the alias name ExtAttribute7
     */
    public String getExtAttribute7() {
        return (String)getAttributeInternal(EXTATTRIBUTE7);
    }

    /**Sets <code>value</code> as the attribute value for ExtAttribute7
     */
    public void setExtAttribute7(String value) {
        setAttributeInternal(EXTATTRIBUTE7, value);
    }

    /**Gets the attribute value for ExtAttribute8, using the alias name ExtAttribute8
     */
    public String getExtAttribute8() {
        return (String)getAttributeInternal(EXTATTRIBUTE8);
    }

    /**Sets <code>value</code> as the attribute value for ExtAttribute8
     */
    public void setExtAttribute8(String value) {
        setAttributeInternal(EXTATTRIBUTE8, value);
    }

    /**Gets the attribute value for ExtAttribute9, using the alias name ExtAttribute9
     */
    public String getExtAttribute9() {
        return (String)getAttributeInternal(EXTATTRIBUTE9);
    }

    /**Sets <code>value</code> as the attribute value for ExtAttribute9
     */
    public void setExtAttribute9(String value) {
        setAttributeInternal(EXTATTRIBUTE9, value);
    }

    /**Gets the attribute value for ExtAttribute10, using the alias name ExtAttribute10
     */
    public String getExtAttribute10() {
        return (String)getAttributeInternal(EXTATTRIBUTE10);
    }

    /**Sets <code>value</code> as the attribute value for ExtAttribute10
     */
    public void setExtAttribute10(String value) {
        setAttributeInternal(EXTATTRIBUTE10, value);
    }

    /**Gets the attribute value for ExtAttribute11, using the alias name ExtAttribute11
     */
    public String getExtAttribute11() {
        return (String)getAttributeInternal(EXTATTRIBUTE11);
    }

    /**Sets <code>value</code> as the attribute value for ExtAttribute11
     */
    public void setExtAttribute11(String value) {
        setAttributeInternal(EXTATTRIBUTE11, value);
    }

    /**Gets the attribute value for ExtAttribute12, using the alias name ExtAttribute12
     */
    public String getExtAttribute12() {
        return (String)getAttributeInternal(EXTATTRIBUTE12);
    }

    /**Sets <code>value</code> as the attribute value for ExtAttribute12
     */
    public void setExtAttribute12(String value) {
        setAttributeInternal(EXTATTRIBUTE12, value);
    }

    /**Gets the attribute value for ExtAttribute13, using the alias name ExtAttribute13
     */
    public String getExtAttribute13() {
        return (String)getAttributeInternal(EXTATTRIBUTE13);
    }

    /**Sets <code>value</code> as the attribute value for ExtAttribute13
     */
    public void setExtAttribute13(String value) {
        setAttributeInternal(EXTATTRIBUTE13, value);
    }

    /**Gets the attribute value for ExtAttribute14, using the alias name ExtAttribute14
     */
    public String getExtAttribute14() {
        return (String)getAttributeInternal(EXTATTRIBUTE14);
    }

    /**Sets <code>value</code> as the attribute value for ExtAttribute14
     */
    public void setExtAttribute14(String value) {
        setAttributeInternal(EXTATTRIBUTE14, value);
    }

    /**Gets the attribute value for ExtAttribute15, using the alias name ExtAttribute15
     */
    public String getExtAttribute15() {
        return (String)getAttributeInternal(EXTATTRIBUTE15);
    }

    /**Sets <code>value</code> as the attribute value for ExtAttribute15
     */
    public void setExtAttribute15(String value) {
        setAttributeInternal(EXTATTRIBUTE15, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case TEAMID:
            return getTeamId();
        case TEAMNAME:
            return getTeamName();
        case TEAMARABICNAME:
            return getTeamArabicName();
        case SHORTNAME:
            return getShortName();
        case TEAMTYPE:
            return getTeamType();
        case SECRETARY:
            return getSecretary();
        case SECRETARYASSISTANT:
            return getSecretaryAssistant();
        case ENDDATE:
            return getEndDate();
        case BUDGETFROM:
            return getBudgetFrom();
        case BUDGETTO:
            return getBudgetTo();
        case DESCRIPTION:
            return getDescription();
        case CREATIONDATE:
            return getCreationDate();
        case CREATEDBY:
            return getCreatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATEBY:
            return getLastUpdateBy();
        case INTATTRIBUTECATEGORY:
            return getIntAttributeCategory();
        case INTATTRIBUTE1:
            return getIntAttribute1();
        case INTATTRIBUTE2:
            return getIntAttribute2();
        case INTATTRIBUTE3:
            return getIntAttribute3();
        case INTATTRIBUTE4:
            return getIntAttribute4();
        case INTATTRIBUTE5:
            return getIntAttribute5();
        case INTATTRIBUTE6:
            return getIntAttribute6();
        case INTATTRIBUTE7:
            return getIntAttribute7();
        case INTATTRIBUTE8:
            return getIntAttribute8();
        case INTATTRIBUTE9:
            return getIntAttribute9();
        case INTATTRIBUTE10:
            return getIntAttribute10();
        case INTATTRIBUTE11:
            return getIntAttribute11();
        case INTATTRIBUTE12:
            return getIntAttribute12();
        case INTATTRIBUTE13:
            return getIntAttribute13();
        case INTATTRIBUTE14:
            return getIntAttribute14();
        case INTATTRIBUTE15:
            return getIntAttribute15();
        case EXTATTRIBUTECATEGORY:
            return getExtAttributeCategory();
        case EXTATTRIBUTE1:
            return getExtAttribute1();
        case EXTATTRIBUTE2:
            return getExtAttribute2();
        case EXTATTRIBUTE3:
            return getExtAttribute3();
        case EXTATTRIBUTE4:
            return getExtAttribute4();
        case EXTATTRIBUTE5:
            return getExtAttribute5();
        case EXTATTRIBUTE6:
            return getExtAttribute6();
        case EXTATTRIBUTE7:
            return getExtAttribute7();
        case EXTATTRIBUTE8:
            return getExtAttribute8();
        case EXTATTRIBUTE9:
            return getExtAttribute9();
        case EXTATTRIBUTE10:
            return getExtAttribute10();
        case EXTATTRIBUTE11:
            return getExtAttribute11();
        case EXTATTRIBUTE12:
            return getExtAttribute12();
        case EXTATTRIBUTE13:
            return getExtAttribute13();
        case EXTATTRIBUTE14:
            return getExtAttribute14();
        case EXTATTRIBUTE15:
            return getExtAttribute15();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case TEAMID:
            setTeamId((Number)value);
            return;
        case TEAMNAME:
            setTeamName((String)value);
            return;
        case TEAMARABICNAME:
            setTeamArabicName((String)value);
            return;
        case SHORTNAME:
            setShortName((String)value);
            return;
        case TEAMTYPE:
            setTeamType((String)value);
            return;
        case SECRETARY:
            setSecretary((String)value);
            return;
        case SECRETARYASSISTANT:
            setSecretaryAssistant((String)value);
            return;
        case ENDDATE:
            setEndDate((Date)value);
            return;
        case BUDGETFROM:
            setBudgetFrom((Number)value);
            return;
        case BUDGETTO:
            setBudgetTo((Number)value);
            return;
        case DESCRIPTION:
            setDescription((String)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATEBY:
            setLastUpdateBy((Number)value);
            return;
        case INTATTRIBUTECATEGORY:
            setIntAttributeCategory((String)value);
            return;
        case INTATTRIBUTE1:
            setIntAttribute1((String)value);
            return;
        case INTATTRIBUTE2:
            setIntAttribute2((String)value);
            return;
        case INTATTRIBUTE3:
            setIntAttribute3((String)value);
            return;
        case INTATTRIBUTE4:
            setIntAttribute4((String)value);
            return;
        case INTATTRIBUTE5:
            setIntAttribute5((String)value);
            return;
        case INTATTRIBUTE6:
            setIntAttribute6((String)value);
            return;
        case INTATTRIBUTE7:
            setIntAttribute7((String)value);
            return;
        case INTATTRIBUTE8:
            setIntAttribute8((String)value);
            return;
        case INTATTRIBUTE9:
            setIntAttribute9((String)value);
            return;
        case INTATTRIBUTE10:
            setIntAttribute10((String)value);
            return;
        case INTATTRIBUTE11:
            setIntAttribute11((String)value);
            return;
        case INTATTRIBUTE12:
            setIntAttribute12((String)value);
            return;
        case INTATTRIBUTE13:
            setIntAttribute13((String)value);
            return;
        case INTATTRIBUTE14:
            setIntAttribute14((String)value);
            return;
        case INTATTRIBUTE15:
            setIntAttribute15((String)value);
            return;
        case EXTATTRIBUTECATEGORY:
            setExtAttributeCategory((String)value);
            return;
        case EXTATTRIBUTE1:
            setExtAttribute1((String)value);
            return;
        case EXTATTRIBUTE2:
            setExtAttribute2((String)value);
            return;
        case EXTATTRIBUTE3:
            setExtAttribute3((String)value);
            return;
        case EXTATTRIBUTE4:
            setExtAttribute4((String)value);
            return;
        case EXTATTRIBUTE5:
            setExtAttribute5((String)value);
            return;
        case EXTATTRIBUTE6:
            setExtAttribute6((String)value);
            return;
        case EXTATTRIBUTE7:
            setExtAttribute7((String)value);
            return;
        case EXTATTRIBUTE8:
            setExtAttribute8((String)value);
            return;
        case EXTATTRIBUTE9:
            setExtAttribute9((String)value);
            return;
        case EXTATTRIBUTE10:
            setExtAttribute10((String)value);
            return;
        case EXTATTRIBUTE11:
            setExtAttribute11((String)value);
            return;
        case EXTATTRIBUTE12:
            setExtAttribute12((String)value);
            return;
        case EXTATTRIBUTE13:
            setExtAttribute13((String)value);
            return;
        case EXTATTRIBUTE14:
            setExtAttribute14((String)value);
            return;
        case EXTATTRIBUTE15:
            setExtAttribute15((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number teamId) {
        return new Key(new Object[]{teamId});
    }
}
