package masterdetail.oracle.apps.fnd.master.schema.server;

import oracle.apps.fnd.framework.server.OAEntityDefImpl;
import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MasterEOImpl extends OAEntityImpl {
    public static final int TEAMID = 0;
    public static final int MEMBERNAME = 1;
    public static final int FIXED = 2;
    public static final int ACCESSTYPE = 3;
    public static final int APPROVER = 4;
    public static final int APPROVESEQUENCE = 5;
    public static final int CHAIRMAN = 6;
    public static final int VICECHAIRMAN = 7;
    public static final int MOF = 8;
    public static final int AUDITOR = 9;
    public static final int HCSS = 10;
    public static final int CDM = 11;
    public static final int HTACS = 12;
    public static final int LASTNOTIFIED = 13;
    public static final int INTATTRIBUTECATEGORY = 14;
    public static final int INTATTRIBUTE1 = 15;
    public static final int INTATTRIBUTE2 = 16;
    public static final int INTATTRIBUTE3 = 17;
    public static final int INTATTRIBUTE4 = 18;
    public static final int INTATTRIBUTE5 = 19;
    public static final int INTATTRIBUTE6 = 20;
    public static final int INTATTRIBUTE7 = 21;
    public static final int INTATTRIBUTE8 = 22;
    public static final int INTATTRIBUTE9 = 23;
    public static final int INTATTRIBUTE10 = 24;
    public static final int INTATTRIBUTE11 = 25;
    public static final int INTATTRIBUTE12 = 26;
    public static final int INTATTRIBUTE13 = 27;
    public static final int INTATTRIBUTE14 = 28;
    public static final int INTATTRIBUTE15 = 29;
    public static final int EXTATTRIBUTECATEGORY = 30;
    public static final int EXTATTRIBUTE1 = 31;
    public static final int EXTATTRIBUTE2 = 32;
    public static final int EXTATTRIBUTE3 = 33;
    public static final int EXTATTRIBUTE4 = 34;
    public static final int EXTATTRIBUTE5 = 35;
    public static final int EXTATTRIBUTE6 = 36;
    public static final int EXTATTRIBUTE7 = 37;
    public static final int EXTATTRIBUTE8 = 38;
    public static final int EXTATTRIBUTE9 = 39;
    public static final int EXTATTRIBUTE10 = 40;
    public static final int EXTATTRIBUTE11 = 41;
    public static final int EXTATTRIBUTE12 = 42;
    public static final int EXTATTRIBUTE13 = 43;
    public static final int EXTATTRIBUTE14 = 44;
    public static final int EXTATTRIBUTE15 = 45;

    private static OAEntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public MasterEOImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = 
                    (OAEntityDefImpl)EntityDefImpl.findDefObject("masterdetail.oracle.apps.fnd.master.schema.server.MasterEO");
        }
        return mDefinitionObject;
    }

    /**Add attribute defaulting logic in this method.
     */
    public void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**Add Entity validation code in this method.
     */
    protected void validateEntity() {
        super.validateEntity();
    }

    /**Gets the attribute value for TeamId, using the alias name TeamId
     */
    public Number getTeamId() {
        return (Number)getAttributeInternal(TEAMID);
    }

    /**Sets <code>value</code> as the attribute value for TeamId
     */
    public void setTeamId(Number value) {
        setAttributeInternal(TEAMID, value);
    }

    /**Gets the attribute value for MemberName, using the alias name MemberName
     */
    public String getMemberName() {
        return (String)getAttributeInternal(MEMBERNAME);
    }

    /**Sets <code>value</code> as the attribute value for MemberName
     */
    public void setMemberName(String value) {
        setAttributeInternal(MEMBERNAME, value);
    }

    /**Gets the attribute value for Fixed, using the alias name Fixed
     */
    public String getFixed() {
        return (String)getAttributeInternal(FIXED);
    }

    /**Sets <code>value</code> as the attribute value for Fixed
     */
    public void setFixed(String value) {
        setAttributeInternal(FIXED, value);
    }

    /**Gets the attribute value for AccessType, using the alias name AccessType
     */
    public String getAccessType() {
        return (String)getAttributeInternal(ACCESSTYPE);
    }

    /**Sets <code>value</code> as the attribute value for AccessType
     */
    public void setAccessType(String value) {
        setAttributeInternal(ACCESSTYPE, value);
    }

    /**Gets the attribute value for Approver, using the alias name Approver
     */
    public String getApprover() {
        return (String)getAttributeInternal(APPROVER);
    }

    /**Sets <code>value</code> as the attribute value for Approver
     */
    public void setApprover(String value) {
        setAttributeInternal(APPROVER, value);
    }

    /**Gets the attribute value for ApproveSequence, using the alias name ApproveSequence
     */
    public Number getApproveSequence() {
        return (Number)getAttributeInternal(APPROVESEQUENCE);
    }

    /**Sets <code>value</code> as the attribute value for ApproveSequence
     */
    public void setApproveSequence(Number value) {
        setAttributeInternal(APPROVESEQUENCE, value);
    }

    /**Gets the attribute value for Chairman, using the alias name Chairman
     */
    public String getChairman() {
        return (String)getAttributeInternal(CHAIRMAN);
    }

    /**Sets <code>value</code> as the attribute value for Chairman
     */
    public void setChairman(String value) {
        setAttributeInternal(CHAIRMAN, value);
    }

    /**Gets the attribute value for ViceChairman, using the alias name ViceChairman
     */
    public String getViceChairman() {
        return (String)getAttributeInternal(VICECHAIRMAN);
    }

    /**Sets <code>value</code> as the attribute value for ViceChairman
     */
    public void setViceChairman(String value) {
        setAttributeInternal(VICECHAIRMAN, value);
    }

    /**Gets the attribute value for Mof, using the alias name Mof
     */
    public String getMof() {
        return (String)getAttributeInternal(MOF);
    }

    /**Sets <code>value</code> as the attribute value for Mof
     */
    public void setMof(String value) {
        setAttributeInternal(MOF, value);
    }

    /**Gets the attribute value for Auditor, using the alias name Auditor
     */
    public String getAuditor() {
        return (String)getAttributeInternal(AUDITOR);
    }

    /**Sets <code>value</code> as the attribute value for Auditor
     */
    public void setAuditor(String value) {
        setAttributeInternal(AUDITOR, value);
    }

    /**Gets the attribute value for Hcss, using the alias name Hcss
     */
    public String getHcss() {
        return (String)getAttributeInternal(HCSS);
    }

    /**Sets <code>value</code> as the attribute value for Hcss
     */
    public void setHcss(String value) {
        setAttributeInternal(HCSS, value);
    }

    /**Gets the attribute value for Cdm, using the alias name Cdm
     */
    public String getCdm() {
        return (String)getAttributeInternal(CDM);
    }

    /**Sets <code>value</code> as the attribute value for Cdm
     */
    public void setCdm(String value) {
        setAttributeInternal(CDM, value);
    }

    /**Gets the attribute value for Htacs, using the alias name Htacs
     */
    public String getHtacs() {
        return (String)getAttributeInternal(HTACS);
    }

    /**Sets <code>value</code> as the attribute value for Htacs
     */
    public void setHtacs(String value) {
        setAttributeInternal(HTACS, value);
    }

    /**Gets the attribute value for Lastnotified, using the alias name Lastnotified
     */
    public Date getLastnotified() {
        return (Date)getAttributeInternal(LASTNOTIFIED);
    }

    /**Sets <code>value</code> as the attribute value for Lastnotified
     */
    public void setLastnotified(Date value) {
        setAttributeInternal(LASTNOTIFIED, value);
    }

    /**Gets the attribute value for IntAttributeCategory, using the alias name IntAttributeCategory
     */
    public String getIntAttributeCategory() {
        return (String)getAttributeInternal(INTATTRIBUTECATEGORY);
    }

    /**Sets <code>value</code> as the attribute value for IntAttributeCategory
     */
    public void setIntAttributeCategory(String value) {
        setAttributeInternal(INTATTRIBUTECATEGORY, value);
    }

    /**Gets the attribute value for IntAttribute1, using the alias name IntAttribute1
     */
    public String getIntAttribute1() {
        return (String)getAttributeInternal(INTATTRIBUTE1);
    }

    /**Sets <code>value</code> as the attribute value for IntAttribute1
     */
    public void setIntAttribute1(String value) {
        setAttributeInternal(INTATTRIBUTE1, value);
    }

    /**Gets the attribute value for IntAttribute2, using the alias name IntAttribute2
     */
    public String getIntAttribute2() {
        return (String)getAttributeInternal(INTATTRIBUTE2);
    }

    /**Sets <code>value</code> as the attribute value for IntAttribute2
     */
    public void setIntAttribute2(String value) {
        setAttributeInternal(INTATTRIBUTE2, value);
    }

    /**Gets the attribute value for IntAttribute3, using the alias name IntAttribute3
     */
    public String getIntAttribute3() {
        return (String)getAttributeInternal(INTATTRIBUTE3);
    }

    /**Sets <code>value</code> as the attribute value for IntAttribute3
     */
    public void setIntAttribute3(String value) {
        setAttributeInternal(INTATTRIBUTE3, value);
    }

    /**Gets the attribute value for IntAttribute4, using the alias name IntAttribute4
     */
    public String getIntAttribute4() {
        return (String)getAttributeInternal(INTATTRIBUTE4);
    }

    /**Sets <code>value</code> as the attribute value for IntAttribute4
     */
    public void setIntAttribute4(String value) {
        setAttributeInternal(INTATTRIBUTE4, value);
    }

    /**Gets the attribute value for IntAttribute5, using the alias name IntAttribute5
     */
    public String getIntAttribute5() {
        return (String)getAttributeInternal(INTATTRIBUTE5);
    }

    /**Sets <code>value</code> as the attribute value for IntAttribute5
     */
    public void setIntAttribute5(String value) {
        setAttributeInternal(INTATTRIBUTE5, value);
    }

    /**Gets the attribute value for IntAttribute6, using the alias name IntAttribute6
     */
    public String getIntAttribute6() {
        return (String)getAttributeInternal(INTATTRIBUTE6);
    }

    /**Sets <code>value</code> as the attribute value for IntAttribute6
     */
    public void setIntAttribute6(String value) {
        setAttributeInternal(INTATTRIBUTE6, value);
    }

    /**Gets the attribute value for IntAttribute7, using the alias name IntAttribute7
     */
    public String getIntAttribute7() {
        return (String)getAttributeInternal(INTATTRIBUTE7);
    }

    /**Sets <code>value</code> as the attribute value for IntAttribute7
     */
    public void setIntAttribute7(String value) {
        setAttributeInternal(INTATTRIBUTE7, value);
    }

    /**Gets the attribute value for IntAttribute8, using the alias name IntAttribute8
     */
    public String getIntAttribute8() {
        return (String)getAttributeInternal(INTATTRIBUTE8);
    }

    /**Sets <code>value</code> as the attribute value for IntAttribute8
     */
    public void setIntAttribute8(String value) {
        setAttributeInternal(INTATTRIBUTE8, value);
    }

    /**Gets the attribute value for IntAttribute9, using the alias name IntAttribute9
     */
    public String getIntAttribute9() {
        return (String)getAttributeInternal(INTATTRIBUTE9);
    }

    /**Sets <code>value</code> as the attribute value for IntAttribute9
     */
    public void setIntAttribute9(String value) {
        setAttributeInternal(INTATTRIBUTE9, value);
    }

    /**Gets the attribute value for IntAttribute10, using the alias name IntAttribute10
     */
    public String getIntAttribute10() {
        return (String)getAttributeInternal(INTATTRIBUTE10);
    }

    /**Sets <code>value</code> as the attribute value for IntAttribute10
     */
    public void setIntAttribute10(String value) {
        setAttributeInternal(INTATTRIBUTE10, value);
    }

    /**Gets the attribute value for IntAttribute11, using the alias name IntAttribute11
     */
    public String getIntAttribute11() {
        return (String)getAttributeInternal(INTATTRIBUTE11);
    }

    /**Sets <code>value</code> as the attribute value for IntAttribute11
     */
    public void setIntAttribute11(String value) {
        setAttributeInternal(INTATTRIBUTE11, value);
    }

    /**Gets the attribute value for IntAttribute12, using the alias name IntAttribute12
     */
    public String getIntAttribute12() {
        return (String)getAttributeInternal(INTATTRIBUTE12);
    }

    /**Sets <code>value</code> as the attribute value for IntAttribute12
     */
    public void setIntAttribute12(String value) {
        setAttributeInternal(INTATTRIBUTE12, value);
    }

    /**Gets the attribute value for IntAttribute13, using the alias name IntAttribute13
     */
    public String getIntAttribute13() {
        return (String)getAttributeInternal(INTATTRIBUTE13);
    }

    /**Sets <code>value</code> as the attribute value for IntAttribute13
     */
    public void setIntAttribute13(String value) {
        setAttributeInternal(INTATTRIBUTE13, value);
    }

    /**Gets the attribute value for IntAttribute14, using the alias name IntAttribute14
     */
    public String getIntAttribute14() {
        return (String)getAttributeInternal(INTATTRIBUTE14);
    }

    /**Sets <code>value</code> as the attribute value for IntAttribute14
     */
    public void setIntAttribute14(String value) {
        setAttributeInternal(INTATTRIBUTE14, value);
    }

    /**Gets the attribute value for IntAttribute15, using the alias name IntAttribute15
     */
    public String getIntAttribute15() {
        return (String)getAttributeInternal(INTATTRIBUTE15);
    }

    /**Sets <code>value</code> as the attribute value for IntAttribute15
     */
    public void setIntAttribute15(String value) {
        setAttributeInternal(INTATTRIBUTE15, value);
    }

    /**Gets the attribute value for ExtAttributeCategory, using the alias name ExtAttributeCategory
     */
    public String getExtAttributeCategory() {
        return (String)getAttributeInternal(EXTATTRIBUTECATEGORY);
    }

    /**Sets <code>value</code> as the attribute value for ExtAttributeCategory
     */
    public void setExtAttributeCategory(String value) {
        setAttributeInternal(EXTATTRIBUTECATEGORY, value);
    }

    /**Gets the attribute value for ExtAttribute1, using the alias name ExtAttribute1
     */
    public String getExtAttribute1() {
        return (String)getAttributeInternal(EXTATTRIBUTE1);
    }

    /**Sets <code>value</code> as the attribute value for ExtAttribute1
     */
    public void setExtAttribute1(String value) {
        setAttributeInternal(EXTATTRIBUTE1, value);
    }

    /**Gets the attribute value for ExtAttribute2, using the alias name ExtAttribute2
     */
    public String getExtAttribute2() {
        return (String)getAttributeInternal(EXTATTRIBUTE2);
    }

    /**Sets <code>value</code> as the attribute value for ExtAttribute2
     */
    public void setExtAttribute2(String value) {
        setAttributeInternal(EXTATTRIBUTE2, value);
    }

    /**Gets the attribute value for ExtAttribute3, using the alias name ExtAttribute3
     */
    public String getExtAttribute3() {
        return (String)getAttributeInternal(EXTATTRIBUTE3);
    }

    /**Sets <code>value</code> as the attribute value for ExtAttribute3
     */
    public void setExtAttribute3(String value) {
        setAttributeInternal(EXTATTRIBUTE3, value);
    }

    /**Gets the attribute value for ExtAttribute4, using the alias name ExtAttribute4
     */
    public String getExtAttribute4() {
        return (String)getAttributeInternal(EXTATTRIBUTE4);
    }

    /**Sets <code>value</code> as the attribute value for ExtAttribute4
     */
    public void setExtAttribute4(String value) {
        setAttributeInternal(EXTATTRIBUTE4, value);
    }

    /**Gets the attribute value for ExtAttribute5, using the alias name ExtAttribute5
     */
    public String getExtAttribute5() {
        return (String)getAttributeInternal(EXTATTRIBUTE5);
    }

    /**Sets <code>value</code> as the attribute value for ExtAttribute5
     */
    public void setExtAttribute5(String value) {
        setAttributeInternal(EXTATTRIBUTE5, value);
    }

    /**Gets the attribute value for ExtAttribute6, using the alias name ExtAttribute6
     */
    public String getExtAttribute6() {
        return (String)getAttributeInternal(EXTATTRIBUTE6);
    }

    /**Sets <code>value</code> as the attribute value for ExtAttribute6
     */
    public void setExtAttribute6(String value) {
        setAttributeInternal(EXTATTRIBUTE6, value);
    }

    /**Gets the attribute value for ExtAttribute7, using the alias name ExtAttribute7
     */
    public String getExtAttribute7() {
        return (String)getAttributeInternal(EXTATTRIBUTE7);
    }

    /**Sets <code>value</code> as the attribute value for ExtAttribute7
     */
    public void setExtAttribute7(String value) {
        setAttributeInternal(EXTATTRIBUTE7, value);
    }

    /**Gets the attribute value for ExtAttribute8, using the alias name ExtAttribute8
     */
    public String getExtAttribute8() {
        return (String)getAttributeInternal(EXTATTRIBUTE8);
    }

    /**Sets <code>value</code> as the attribute value for ExtAttribute8
     */
    public void setExtAttribute8(String value) {
        setAttributeInternal(EXTATTRIBUTE8, value);
    }

    /**Gets the attribute value for ExtAttribute9, using the alias name ExtAttribute9
     */
    public String getExtAttribute9() {
        return (String)getAttributeInternal(EXTATTRIBUTE9);
    }

    /**Sets <code>value</code> as the attribute value for ExtAttribute9
     */
    public void setExtAttribute9(String value) {
        setAttributeInternal(EXTATTRIBUTE9, value);
    }

    /**Gets the attribute value for ExtAttribute10, using the alias name ExtAttribute10
     */
    public String getExtAttribute10() {
        return (String)getAttributeInternal(EXTATTRIBUTE10);
    }

    /**Sets <code>value</code> as the attribute value for ExtAttribute10
     */
    public void setExtAttribute10(String value) {
        setAttributeInternal(EXTATTRIBUTE10, value);
    }

    /**Gets the attribute value for ExtAttribute11, using the alias name ExtAttribute11
     */
    public String getExtAttribute11() {
        return (String)getAttributeInternal(EXTATTRIBUTE11);
    }

    /**Sets <code>value</code> as the attribute value for ExtAttribute11
     */
    public void setExtAttribute11(String value) {
        setAttributeInternal(EXTATTRIBUTE11, value);
    }

    /**Gets the attribute value for ExtAttribute12, using the alias name ExtAttribute12
     */
    public String getExtAttribute12() {
        return (String)getAttributeInternal(EXTATTRIBUTE12);
    }

    /**Sets <code>value</code> as the attribute value for ExtAttribute12
     */
    public void setExtAttribute12(String value) {
        setAttributeInternal(EXTATTRIBUTE12, value);
    }

    /**Gets the attribute value for ExtAttribute13, using the alias name ExtAttribute13
     */
    public String getExtAttribute13() {
        return (String)getAttributeInternal(EXTATTRIBUTE13);
    }

    /**Sets <code>value</code> as the attribute value for ExtAttribute13
     */
    public void setExtAttribute13(String value) {
        setAttributeInternal(EXTATTRIBUTE13, value);
    }

    /**Gets the attribute value for ExtAttribute14, using the alias name ExtAttribute14
     */
    public String getExtAttribute14() {
        return (String)getAttributeInternal(EXTATTRIBUTE14);
    }

    /**Sets <code>value</code> as the attribute value for ExtAttribute14
     */
    public void setExtAttribute14(String value) {
        setAttributeInternal(EXTATTRIBUTE14, value);
    }

    /**Gets the attribute value for ExtAttribute15, using the alias name ExtAttribute15
     */
    public String getExtAttribute15() {
        return (String)getAttributeInternal(EXTATTRIBUTE15);
    }

    /**Sets <code>value</code> as the attribute value for ExtAttribute15
     */
    public void setExtAttribute15(String value) {
        setAttributeInternal(EXTATTRIBUTE15, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case TEAMID:
            return getTeamId();
        case MEMBERNAME:
            return getMemberName();
        case FIXED:
            return getFixed();
        case ACCESSTYPE:
            return getAccessType();
        case APPROVER:
            return getApprover();
        case APPROVESEQUENCE:
            return getApproveSequence();
        case CHAIRMAN:
            return getChairman();
        case VICECHAIRMAN:
            return getViceChairman();
        case MOF:
            return getMof();
        case AUDITOR:
            return getAuditor();
        case HCSS:
            return getHcss();
        case CDM:
            return getCdm();
        case HTACS:
            return getHtacs();
        case LASTNOTIFIED:
            return getLastnotified();
        case INTATTRIBUTECATEGORY:
            return getIntAttributeCategory();
        case INTATTRIBUTE1:
            return getIntAttribute1();
        case INTATTRIBUTE2:
            return getIntAttribute2();
        case INTATTRIBUTE3:
            return getIntAttribute3();
        case INTATTRIBUTE4:
            return getIntAttribute4();
        case INTATTRIBUTE5:
            return getIntAttribute5();
        case INTATTRIBUTE6:
            return getIntAttribute6();
        case INTATTRIBUTE7:
            return getIntAttribute7();
        case INTATTRIBUTE8:
            return getIntAttribute8();
        case INTATTRIBUTE9:
            return getIntAttribute9();
        case INTATTRIBUTE10:
            return getIntAttribute10();
        case INTATTRIBUTE11:
            return getIntAttribute11();
        case INTATTRIBUTE12:
            return getIntAttribute12();
        case INTATTRIBUTE13:
            return getIntAttribute13();
        case INTATTRIBUTE14:
            return getIntAttribute14();
        case INTATTRIBUTE15:
            return getIntAttribute15();
        case EXTATTRIBUTECATEGORY:
            return getExtAttributeCategory();
        case EXTATTRIBUTE1:
            return getExtAttribute1();
        case EXTATTRIBUTE2:
            return getExtAttribute2();
        case EXTATTRIBUTE3:
            return getExtAttribute3();
        case EXTATTRIBUTE4:
            return getExtAttribute4();
        case EXTATTRIBUTE5:
            return getExtAttribute5();
        case EXTATTRIBUTE6:
            return getExtAttribute6();
        case EXTATTRIBUTE7:
            return getExtAttribute7();
        case EXTATTRIBUTE8:
            return getExtAttribute8();
        case EXTATTRIBUTE9:
            return getExtAttribute9();
        case EXTATTRIBUTE10:
            return getExtAttribute10();
        case EXTATTRIBUTE11:
            return getExtAttribute11();
        case EXTATTRIBUTE12:
            return getExtAttribute12();
        case EXTATTRIBUTE13:
            return getExtAttribute13();
        case EXTATTRIBUTE14:
            return getExtAttribute14();
        case EXTATTRIBUTE15:
            return getExtAttribute15();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case TEAMID:
            setTeamId((Number)value);
            return;
        case MEMBERNAME:
            setMemberName((String)value);
            return;
        case FIXED:
            setFixed((String)value);
            return;
        case ACCESSTYPE:
            setAccessType((String)value);
            return;
        case APPROVER:
            setApprover((String)value);
            return;
        case APPROVESEQUENCE:
            setApproveSequence((Number)value);
            return;
        case CHAIRMAN:
            setChairman((String)value);
            return;
        case VICECHAIRMAN:
            setViceChairman((String)value);
            return;
        case MOF:
            setMof((String)value);
            return;
        case AUDITOR:
            setAuditor((String)value);
            return;
        case HCSS:
            setHcss((String)value);
            return;
        case CDM:
            setCdm((String)value);
            return;
        case HTACS:
            setHtacs((String)value);
            return;
        case LASTNOTIFIED:
            setLastnotified((Date)value);
            return;
        case INTATTRIBUTECATEGORY:
            setIntAttributeCategory((String)value);
            return;
        case INTATTRIBUTE1:
            setIntAttribute1((String)value);
            return;
        case INTATTRIBUTE2:
            setIntAttribute2((String)value);
            return;
        case INTATTRIBUTE3:
            setIntAttribute3((String)value);
            return;
        case INTATTRIBUTE4:
            setIntAttribute4((String)value);
            return;
        case INTATTRIBUTE5:
            setIntAttribute5((String)value);
            return;
        case INTATTRIBUTE6:
            setIntAttribute6((String)value);
            return;
        case INTATTRIBUTE7:
            setIntAttribute7((String)value);
            return;
        case INTATTRIBUTE8:
            setIntAttribute8((String)value);
            return;
        case INTATTRIBUTE9:
            setIntAttribute9((String)value);
            return;
        case INTATTRIBUTE10:
            setIntAttribute10((String)value);
            return;
        case INTATTRIBUTE11:
            setIntAttribute11((String)value);
            return;
        case INTATTRIBUTE12:
            setIntAttribute12((String)value);
            return;
        case INTATTRIBUTE13:
            setIntAttribute13((String)value);
            return;
        case INTATTRIBUTE14:
            setIntAttribute14((String)value);
            return;
        case INTATTRIBUTE15:
            setIntAttribute15((String)value);
            return;
        case EXTATTRIBUTECATEGORY:
            setExtAttributeCategory((String)value);
            return;
        case EXTATTRIBUTE1:
            setExtAttribute1((String)value);
            return;
        case EXTATTRIBUTE2:
            setExtAttribute2((String)value);
            return;
        case EXTATTRIBUTE3:
            setExtAttribute3((String)value);
            return;
        case EXTATTRIBUTE4:
            setExtAttribute4((String)value);
            return;
        case EXTATTRIBUTE5:
            setExtAttribute5((String)value);
            return;
        case EXTATTRIBUTE6:
            setExtAttribute6((String)value);
            return;
        case EXTATTRIBUTE7:
            setExtAttribute7((String)value);
            return;
        case EXTATTRIBUTE8:
            setExtAttribute8((String)value);
            return;
        case EXTATTRIBUTE9:
            setExtAttribute9((String)value);
            return;
        case EXTATTRIBUTE10:
            setExtAttribute10((String)value);
            return;
        case EXTATTRIBUTE11:
            setExtAttribute11((String)value);
            return;
        case EXTATTRIBUTE12:
            setExtAttribute12((String)value);
            return;
        case EXTATTRIBUTE13:
            setExtAttribute13((String)value);
            return;
        case EXTATTRIBUTE14:
            setExtAttribute14((String)value);
            return;
        case EXTATTRIBUTE15:
            setExtAttribute15((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number teamId) {
        return new Key(new Object[]{teamId});
    }
}
