package masterdetail.oracle.apps.fnd.master.server;

import masterdetail.oracle.apps.fnd.master.schema.server.DetailEOImpl;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DetailVORowImpl extends OAViewRowImpl {
    public static final int TEAMID = 0;
    public static final int TEAMNAME = 1;
    public static final int TEAMARABICNAME = 2;
    public static final int SHORTNAME = 3;
    public static final int TEAMTYPE = 4;
    public static final int SECRETARY = 5;
    public static final int SECRETARYASSISTANT = 6;
    public static final int ENDDATE = 7;
    public static final int BUDGETFROM = 8;
    public static final int BUDGETTO = 9;
    public static final int DESCRIPTION = 10;
    public static final int CREATIONDATE = 11;
    public static final int CREATEDBY = 12;
    public static final int LASTUPDATEDATE = 13;
    public static final int LASTUPDATEBY = 14;

    /**This is the default constructor (do not remove)
     */
    public DetailVORowImpl() {
    }

    /**Gets DetailEO entity object.
     */
    public DetailEOImpl getDetailEO() {
        return (DetailEOImpl)getEntity(0);
    }

    /**Gets the attribute value for TEAM_ID using the alias name TeamId
     */
    public Number getTeamId() {
        return (Number) getAttributeInternal(TEAMID);
    }

    /**Sets <code>value</code> as attribute value for TEAM_ID using the alias name TeamId
     */
    public void setTeamId(Number value) {
        setAttributeInternal(TEAMID, value);
    }

    /**Gets the attribute value for TEAM_NAME using the alias name TeamName
     */
    public String getTeamName() {
        return (String) getAttributeInternal(TEAMNAME);
    }

    /**Sets <code>value</code> as attribute value for TEAM_NAME using the alias name TeamName
     */
    public void setTeamName(String value) {
        setAttributeInternal(TEAMNAME, value);
    }

    /**Gets the attribute value for TEAM_ARABIC_NAME using the alias name TeamArabicName
     */
    public String getTeamArabicName() {
        return (String) getAttributeInternal(TEAMARABICNAME);
    }

    /**Sets <code>value</code> as attribute value for TEAM_ARABIC_NAME using the alias name TeamArabicName
     */
    public void setTeamArabicName(String value) {
        setAttributeInternal(TEAMARABICNAME, value);
    }

    /**Gets the attribute value for SHORT_NAME using the alias name ShortName
     */
    public String getShortName() {
        return (String) getAttributeInternal(SHORTNAME);
    }

    /**Sets <code>value</code> as attribute value for SHORT_NAME using the alias name ShortName
     */
    public void setShortName(String value) {
        setAttributeInternal(SHORTNAME, value);
    }

    /**Gets the attribute value for TEAM_TYPE using the alias name TeamType
     */
    public String getTeamType() {
        return (String) getAttributeInternal(TEAMTYPE);
    }

    /**Sets <code>value</code> as attribute value for TEAM_TYPE using the alias name TeamType
     */
    public void setTeamType(String value) {
        setAttributeInternal(TEAMTYPE, value);
    }

    /**Gets the attribute value for SECRETARY using the alias name Secretary
     */
    public String getSecretary() {
        return (String) getAttributeInternal(SECRETARY);
    }

    /**Sets <code>value</code> as attribute value for SECRETARY using the alias name Secretary
     */
    public void setSecretary(String value) {
        setAttributeInternal(SECRETARY, value);
    }

    /**Gets the attribute value for SECRETARY_ASSISTANT using the alias name SecretaryAssistant
     */
    public String getSecretaryAssistant() {
        return (String) getAttributeInternal(SECRETARYASSISTANT);
    }

    /**Sets <code>value</code> as attribute value for SECRETARY_ASSISTANT using the alias name SecretaryAssistant
     */
    public void setSecretaryAssistant(String value) {
        setAttributeInternal(SECRETARYASSISTANT, value);
    }

    /**Gets the attribute value for END_DATE using the alias name EndDate
     */
    public Date getEndDate() {
        return (Date) getAttributeInternal(ENDDATE);
    }

    /**Sets <code>value</code> as attribute value for END_DATE using the alias name EndDate
     */
    public void setEndDate(Date value) {
        setAttributeInternal(ENDDATE, value);
    }

    /**Gets the attribute value for BUDGET_FROM using the alias name BudgetFrom
     */
    public Number getBudgetFrom() {
        return (Number) getAttributeInternal(BUDGETFROM);
    }

    /**Sets <code>value</code> as attribute value for BUDGET_FROM using the alias name BudgetFrom
     */
    public void setBudgetFrom(Number value) {
        setAttributeInternal(BUDGETFROM, value);
    }

    /**Gets the attribute value for BUDGET_TO using the alias name BudgetTo
     */
    public Number getBudgetTo() {
        return (Number) getAttributeInternal(BUDGETTO);
    }

    /**Sets <code>value</code> as attribute value for BUDGET_TO using the alias name BudgetTo
     */
    public void setBudgetTo(Number value) {
        setAttributeInternal(BUDGETTO, value);
    }

    /**Gets the attribute value for DESCRIPTION using the alias name Description
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**Sets <code>value</code> as attribute value for DESCRIPTION using the alias name Description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**Gets the attribute value for CREATION_DATE using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for CREATED_BY using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATE_DATE using the alias name LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LAST_UPDATE_BY using the alias name LastUpdateBy
     */
    public Number getLastUpdateBy() {
        return (Number) getAttributeInternal(LASTUPDATEBY);
    }

    /**Sets <code>value</code> as attribute value for LAST_UPDATE_BY using the alias name LastUpdateBy
     */
    public void setLastUpdateBy(Number value) {
        setAttributeInternal(LASTUPDATEBY, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case TEAMID:
            return getTeamId();
        case TEAMNAME:
            return getTeamName();
        case TEAMARABICNAME:
            return getTeamArabicName();
        case SHORTNAME:
            return getShortName();
        case TEAMTYPE:
            return getTeamType();
        case SECRETARY:
            return getSecretary();
        case SECRETARYASSISTANT:
            return getSecretaryAssistant();
        case ENDDATE:
            return getEndDate();
        case BUDGETFROM:
            return getBudgetFrom();
        case BUDGETTO:
            return getBudgetTo();
        case DESCRIPTION:
            return getDescription();
        case CREATIONDATE:
            return getCreationDate();
        case CREATEDBY:
            return getCreatedBy();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATEBY:
            return getLastUpdateBy();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case TEAMID:
            setTeamId((Number)value);
            return;
        case TEAMNAME:
            setTeamName((String)value);
            return;
        case TEAMARABICNAME:
            setTeamArabicName((String)value);
            return;
        case SHORTNAME:
            setShortName((String)value);
            return;
        case TEAMTYPE:
            setTeamType((String)value);
            return;
        case SECRETARY:
            setSecretary((String)value);
            return;
        case SECRETARYASSISTANT:
            setSecretaryAssistant((String)value);
            return;
        case ENDDATE:
            setEndDate((Date)value);
            return;
        case BUDGETFROM:
            setBudgetFrom((Number)value);
            return;
        case BUDGETTO:
            setBudgetTo((Number)value);
            return;
        case DESCRIPTION:
            setDescription((String)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATEBY:
            setLastUpdateBy((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
