package masterdetail.oracle.apps.fnd.master.server;

import masterdetail.oracle.apps.fnd.master.schema.server.MasterEOImpl;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MasterVORowImpl extends OAViewRowImpl {
    public static final int TEAMID = 0;
    public static final int MEMBERNAME = 1;
    public static final int FIXED = 2;
    public static final int ACCESSTYPE = 3;
    public static final int APPROVER = 4;
    public static final int APPROVESEQUENCE = 5;
    public static final int CHAIRMAN = 6;
    public static final int VICECHAIRMAN = 7;
    public static final int MOF = 8;
    public static final int AUDITOR = 9;
    public static final int HCSS = 10;
    public static final int CDM = 11;
    public static final int HTACS = 12;
    public static final int LASTNOTIFIED = 13;
    public static final int SELECTFLAG = 14;

    /**This is the default constructor (do not remove)
     */
    public MasterVORowImpl() {
    }

    /**Gets MasterEO entity object.
     */
    public MasterEOImpl getMasterEO() {
        return (MasterEOImpl)getEntity(0);
    }

    /**Gets the attribute value for TEAM_ID using the alias name TeamId
     */
    public Number getTeamId() {
        return (Number) getAttributeInternal(TEAMID);
    }

    /**Sets <code>value</code> as attribute value for TEAM_ID using the alias name TeamId
     */
    public void setTeamId(Number value) {
        setAttributeInternal(TEAMID, value);
    }

    /**Gets the attribute value for MEMBER_NAME using the alias name MemberName
     */
    public String getMemberName() {
        return (String) getAttributeInternal(MEMBERNAME);
    }

    /**Sets <code>value</code> as attribute value for MEMBER_NAME using the alias name MemberName
     */
    public void setMemberName(String value) {
        setAttributeInternal(MEMBERNAME, value);
    }

    /**Gets the attribute value for FIXED using the alias name Fixed
     */
    public String getFixed() {
        return (String) getAttributeInternal(FIXED);
    }

    /**Sets <code>value</code> as attribute value for FIXED using the alias name Fixed
     */
    public void setFixed(String value) {
        setAttributeInternal(FIXED, value);
    }

    /**Gets the attribute value for ACCESS_TYPE using the alias name AccessType
     */
    public String getAccessType() {
        return (String) getAttributeInternal(ACCESSTYPE);
    }

    /**Sets <code>value</code> as attribute value for ACCESS_TYPE using the alias name AccessType
     */
    public void setAccessType(String value) {
        setAttributeInternal(ACCESSTYPE, value);
    }

    /**Gets the attribute value for APPROVER using the alias name Approver
     */
    public String getApprover() {
        return (String) getAttributeInternal(APPROVER);
    }

    /**Sets <code>value</code> as attribute value for APPROVER using the alias name Approver
     */
    public void setApprover(String value) {
        setAttributeInternal(APPROVER, value);
    }

    /**Gets the attribute value for APPROVE_SEQUENCE using the alias name ApproveSequence
     */
    public Number getApproveSequence() {
        return (Number) getAttributeInternal(APPROVESEQUENCE);
    }

    /**Sets <code>value</code> as attribute value for APPROVE_SEQUENCE using the alias name ApproveSequence
     */
    public void setApproveSequence(Number value) {
        setAttributeInternal(APPROVESEQUENCE, value);
    }

    /**Gets the attribute value for CHAIRMAN using the alias name Chairman
     */
    public String getChairman() {
        return (String) getAttributeInternal(CHAIRMAN);
    }

    /**Sets <code>value</code> as attribute value for CHAIRMAN using the alias name Chairman
     */
    public void setChairman(String value) {
        setAttributeInternal(CHAIRMAN, value);
    }

    /**Gets the attribute value for VICE_CHAIRMAN using the alias name ViceChairman
     */
    public String getViceChairman() {
        return (String) getAttributeInternal(VICECHAIRMAN);
    }

    /**Sets <code>value</code> as attribute value for VICE_CHAIRMAN using the alias name ViceChairman
     */
    public void setViceChairman(String value) {
        setAttributeInternal(VICECHAIRMAN, value);
    }

    /**Gets the attribute value for MOF using the alias name Mof
     */
    public String getMof() {
        return (String) getAttributeInternal(MOF);
    }

    /**Sets <code>value</code> as attribute value for MOF using the alias name Mof
     */
    public void setMof(String value) {
        setAttributeInternal(MOF, value);
    }

    /**Gets the attribute value for AUDITOR using the alias name Auditor
     */
    public String getAuditor() {
        return (String) getAttributeInternal(AUDITOR);
    }

    /**Sets <code>value</code> as attribute value for AUDITOR using the alias name Auditor
     */
    public void setAuditor(String value) {
        setAttributeInternal(AUDITOR, value);
    }

    /**Gets the attribute value for HCSS using the alias name Hcss
     */
    public String getHcss() {
        return (String) getAttributeInternal(HCSS);
    }

    /**Sets <code>value</code> as attribute value for HCSS using the alias name Hcss
     */
    public void setHcss(String value) {
        setAttributeInternal(HCSS, value);
    }

    /**Gets the attribute value for CDM using the alias name Cdm
     */
    public String getCdm() {
        return (String) getAttributeInternal(CDM);
    }

    /**Sets <code>value</code> as attribute value for CDM using the alias name Cdm
     */
    public void setCdm(String value) {
        setAttributeInternal(CDM, value);
    }

    /**Gets the attribute value for HTACS using the alias name Htacs
     */
    public String getHtacs() {
        return (String) getAttributeInternal(HTACS);
    }

    /**Sets <code>value</code> as attribute value for HTACS using the alias name Htacs
     */
    public void setHtacs(String value) {
        setAttributeInternal(HTACS, value);
    }

    /**Gets the attribute value for LASTNOTIFIED using the alias name Lastnotified
     */
    public Date getLastnotified() {
        return (Date) getAttributeInternal(LASTNOTIFIED);
    }

    /**Sets <code>value</code> as attribute value for LASTNOTIFIED using the alias name Lastnotified
     */
    public void setLastnotified(Date value) {
        setAttributeInternal(LASTNOTIFIED, value);
    }

    /**Gets the attribute value for the calculated attribute SelectFlag
     */
    public Boolean getSelectFlag() {
        return (Boolean) getAttributeInternal(SELECTFLAG);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SelectFlag
     */
    public void setSelectFlag(Boolean value) {
        setAttributeInternal(SELECTFLAG, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index, 
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case TEAMID:
            return getTeamId();
        case MEMBERNAME:
            return getMemberName();
        case FIXED:
            return getFixed();
        case ACCESSTYPE:
            return getAccessType();
        case APPROVER:
            return getApprover();
        case APPROVESEQUENCE:
            return getApproveSequence();
        case CHAIRMAN:
            return getChairman();
        case VICECHAIRMAN:
            return getViceChairman();
        case MOF:
            return getMof();
        case AUDITOR:
            return getAuditor();
        case HCSS:
            return getHcss();
        case CDM:
            return getCdm();
        case HTACS:
            return getHtacs();
        case LASTNOTIFIED:
            return getLastnotified();
        case SELECTFLAG:
            return getSelectFlag();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value, 
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case TEAMID:
            setTeamId((Number)value);
            return;
        case MEMBERNAME:
            setMemberName((String)value);
            return;
        case FIXED:
            setFixed((String)value);
            return;
        case ACCESSTYPE:
            setAccessType((String)value);
            return;
        case APPROVER:
            setApprover((String)value);
            return;
        case APPROVESEQUENCE:
            setApproveSequence((Number)value);
            return;
        case CHAIRMAN:
            setChairman((String)value);
            return;
        case VICECHAIRMAN:
            setViceChairman((String)value);
            return;
        case MOF:
            setMof((String)value);
            return;
        case AUDITOR:
            setAuditor((String)value);
            return;
        case HCSS:
            setHcss((String)value);
            return;
        case CDM:
            setCdm((String)value);
            return;
        case HTACS:
            setHtacs((String)value);
            return;
        case LASTNOTIFIED:
            setLastnotified((Date)value);
            return;
        case SELECTFLAG:
            setSelectFlag((Boolean)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
