package masterdetail.oracle.apps.fnd.master.server;

import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MasterDetailsAMImpl extends OAApplicationModuleImpl {
    /**This is the default constructor (do not remove)
     */
    public MasterDetailsAMImpl() {
    }

    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) {
        launchTester("masterdetail.oracle.apps.fnd.master.server", /* package name */
      "MasterDetailsAMLocal" /* Configuration Name */);
    }
}
